### ISSUE TITLE
Crash when an MCA Villager is turned into a Zombie.

### ISSUE THREAD

**Issue by Ariannae** [WildBamaBoy/minecraft-comes-alive#628]
Crash:
------------------------------------------------------------------------------------------------------------------------------

> MultiMC version: 0.4.10-733
> 
> Minecraft folder is:
> instances/MCA Villager Zombie Crash/minecraft
> 
> Java path is:
> C:/Program Files/Java/jre1.8.0_31/bin/javaw.exe
> 
> Java Arguments:
> [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Arianna/Desktop/MultiMC/jars/NewLaunch.jar]
> 
> Minecraft process ID: 8124
> 
> Using onesix launcher.
> 
> Main Class:
>   net.minecraft.launchwrapper.Launch
> 
> Native path:
>   C:/Users/Arianna/Desktop/MultiMC/instances/MCA Villager Zombie Crash/natives
> 
> Traits:
>   []
> 
> Libraries:
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
>   C:/Users/Arianna/Desktop/MultiMC/versions/1.7.10/1.7.10.jar
> 
> Mods:
>   MCA-1.7.10-5.1.1.2-universal
>   RadixCore-1.7.10-2.1.1-universal (1)
> 
> Params:
>   [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Arianna/Desktop/MultiMC/instances/MCA Villager Zombie Crash/minecraft, --assetsDir, C:/Users/Arianna/Desktop/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]
> 
> Window size: 854 x 480
> 
> Preparing native libraries...
> Extracting twitch-platform-5.16-natives-windows-64.jar
> Extracting twitch-external-platform-4.5-natives-windows-64.jar
> Extracting jinput-platform-2.0.5-natives-windows.jar
> Extracting lwjgl-platform-2.9.1-natives-windows.jar
> 
> [19:42:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
> [19:42:20] [main/INFO] [FML]: Forge Mod Loader version 7.99.39.1566 for Minecraft 1.7.10 loading
> [19:42:20] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_31
> [19:42:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
> [19:42:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
> [19:42:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
> [19:42:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
> [19:42:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
> [19:42:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
> [19:42:22] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
> [19:42:22] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
> [19:42:22] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
> [19:42:23] [main/INFO]: Setting user: <PROFILE NAME>
> [19:42:24] [Client thread/INFO]: LWJGL Version: 2.9.1
> [19:42:24] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
> [19:42:24] [Client thread/ERROR] [FML]: Could not save the splash.properties file
> java.io.FileNotFoundException: C:\Users\Arianna\Desktop\MultiMC\instances\MCA Villager Zombie Crash\minecraft\config\splash.properties (The system cannot find the path specified)
> 	at java.io.FileOutputStream.open(Native Method) ~[?:1.8.0_31]
> 	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_31]
> 	at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_31]
> 	at java.io.FileWriter.<init>(Unknown Source) ~[?:1.8.0_31]
> 	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:151) [SplashProgress.class:?]
> 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:193) [FMLClientHandler.class:?]
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
> [19:42:24] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 2/5/16 7:42 PM
> Description: Loading screen debug info
> 
> This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_31, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 470100264 bytes (448 MB) / 649592832 bytes (619 MB) up to 954728448 bytes (910 MB)
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.3.0' Renderer: 'GeForce GTS 450/PCIe/SSE2'
> [19:42:25] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
> [19:42:25] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1566 Initialized
> [19:42:25] [Client thread/INFO] [FML]: Replaced 183 ore recipies
> [19:42:25] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
> [19:42:25] [Client thread/INFO] [FML]: Config directory created successfully
> [19:42:25] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
> [19:42:25] [Client thread/INFO] [FML]: Searching C:\Users\Arianna\Desktop\MultiMC\instances\MCA Villager Zombie Crash\minecraft\mods for mods
> [19:42:30] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
> [19:42:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, MCA, RadixCore] at CLIENT
> [19:42:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, MCA, RadixCore] at SERVER
> [19:42:30] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Minecraft Comes Alive, FMLFileResourcePack:RadixCore
> [19:42:30] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
> [19:42:30] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
> [19:42:30] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
> [19:42:30] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
> [19:42:30] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
> [19:42:31] [Client thread/INFO] [RadixCore]: Loaded language en_US for mca.
> [19:42:31] [Client thread/INFO] [FML]: Applying holder lookups
> [19:42:31] [Client thread/INFO] [FML]: Holder lookups applied
> [19:42:31] [Client thread/INFO] [FML]: Injecting itemstacks
> [19:42:31] [Client thread/INFO] [FML]: Itemstack injection complete
> [19:42:31] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:31] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
> [19:42:31] [Thread-7/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
> [19:42:31] [Thread-7/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [19:42:31] [Thread-7/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
> [19:42:31] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
> [19:42:31] [Client thread/INFO]: Created: 16x16 textures/items-atlas
> [19:42:31] [Client thread/INFO] [FML]: Injecting itemstacks
> [19:42:31] [Client thread/INFO] [FML]: Itemstack injection complete
> [19:42:31] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:31] [Sound Library Loader/INFO]: Sound engine started
> [19:42:32] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
> [19:42:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Minecraft Comes Alive, FMLFileResourcePack:RadixCore
> [19:42:32] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
> [19:42:32] [Client thread/INFO]: Created: 512x256 textures/items-atlas
> [19:42:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
> [19:42:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
> [19:42:32] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:32] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:32] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
> [19:42:33] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
> [19:42:33] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [19:42:33] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
> [19:42:33] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
> [19:42:33] [Sound Library Loader/INFO]: Sound engine started
> [19:42:55] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
> [19:42:55] [Server thread/INFO]: Generating keypair
> [19:42:55] [Server thread/INFO]: Converting map!
> [19:42:55] [Server thread/INFO]: Scanning folders...
> [19:42:55] [Server thread/INFO]: Total conversion count is 0
> [19:42:55] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
> [19:42:55] [Server thread/INFO] [FML]: Applying holder lookups
> [19:42:55] [Server thread/INFO] [FML]: Holder lookups applied
> [19:42:56] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@2181e4b3)
> [19:42:56] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@2181e4b3)
> [19:42:56] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@2181e4b3)
> [19:42:56] [Server thread/INFO]: Preparing start region for level 0
> [19:42:57] [Server thread/INFO]: Preparing spawn area: 11%
> [19:42:58] [Server thread/INFO]: Preparing spawn area: 31%
> [19:42:59] [Server thread/INFO]: Preparing spawn area: 49%
> [19:43:00] [Server thread/INFO]: Preparing spawn area: 64%
> [19:43:01] [Server thread/INFO]: Preparing spawn area: 79%
> [19:43:02] [Server thread/INFO]: Preparing spawn area: 96%
> [19:43:02] [Server thread/INFO]: Changing view distance to 12, from 10
> [19:43:02] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
> [19:43:02] [Netty IO #1/INFO] [FML]: Client protocol version 2
> [19:43:02] [Netty IO #1/INFO] [FML]: Client attempting to join with 5 mods : FML@7.10.99.99,RadixCore@2.1.1,Forge@10.13.4.1566,MCA@1.7.10-5.1.1.2,mcp@9.05
> [19:43:02] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
> [19:43:02] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
> [19:43:02] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [19:43:02] [Server thread/INFO]: <PROFILE NAME>[local:E:bd73c502] logged in with entity id 287 at (-173.5, 70.0, 195.5)
> [19:43:02] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
> [19:43:02] [Server thread/INFO]: <PROFILE NAME> joined the game
> [19:43:03] [Client thread/INFO] [MCA]: Received and applied server-side configuration.
> [19:43:04] [Server thread/INFO]: Saving and pausing game...
> [19:43:04] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
> [19:43:06] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
> [19:43:06] [Server thread/INFO]: Saving chunks for level 'New World'/The End
> [19:43:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3822ms behind, skipping 76 tick(s)
> [19:43:20] [Server thread/INFO]: <PROFILE NAME> has just earned the achievement [Taking Inventory]
> [19:43:20] [Client thread/INFO]: [CHAT] <PROFILE NAME> has just earned the achievement [Taking Inventory]
> [19:43:21] [Client thread/INFO]: Warning: Clientside chunk ticking took 204 ms
> [19:43:24] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2752ms behind, skipping 55 tick(s)
> [19:43:29] [Client thread/INFO]: Warning: Clientside chunk ticking took 162 ms
> [19:43:32] [Client thread/INFO]: Warning: Clientside chunk ticking took 119 ms
> [19:43:32] [Client thread/INFO]: Warning: Clientside chunk ticking took 207 ms
> [19:43:33] [Client thread/INFO]: Warning: Clientside chunk ticking took 197 ms
> [19:43:33] [Client thread/INFO]: Warning: Clientside chunk ticking took 179 ms
> [19:43:46] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 9136ms behind, skipping 182 tick(s)
> [19:43:57] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3938ms behind, skipping 78 tick(s)
> [19:44:13] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4320ms behind, skipping 86 tick(s)
> [19:45:00] [Client thread/INFO]: [CHAT] Ashton the Fisherman: What's going on with you today?
> [19:45:00] [Client thread/INFO]: [CHAT] Hunter the Archer: How are you today?
> [19:45:01] [Client thread/INFO]: [CHAT] Brett the Leatherworker: Hey! How are you today?
> [19:45:03] [Server thread/INFO]: [<PROFILE NAME>: Set the time to 13000]
> [19:45:03] [Client thread/INFO]: [CHAT] Set the time to 13000
> [19:45:24] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.util.ReportedException: Ticking entity
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18) ~[tu.class:?]
> 	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93) ~[uq.class:?]
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103) ~[uj.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540) ~[sw.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) ~[sv.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25) ~[yg.class:?]
> 	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217) ~[yq.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30) ~[yg.class:?]
> 	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303) ~[yq.class:?]
> 	at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
> 	at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
> 	at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
> 	... 4 more
> [19:45:24] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Arianna\Desktop\MultiMC\instances\MCA Villager Zombie Crash\minecraft\crash-reports\crash-2016-02-05_19.45.24-server.txt
> [19:45:24] [Server thread/INFO]: Stopping server
> [19:45:24] [Server thread/INFO]: Saving players
> [19:45:24] [Server thread/INFO]: Saving worlds
> [19:45:24] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
> [19:45:24] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
> // This doesn't make any sense!
> 
> Time: 2/5/16 7:45 PM
> Description: Ticking entity
> 
> java.lang.NullPointerException: Ticking entity
> 	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
> 	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
> 	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
> 	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
> 	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
> 	at net.minecraft.world.World.func_72866_a(World.java:2070)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
> 	at net.minecraft.world.World.func_72870_g(World.java:2034)
> 	at net.minecraft.world.World.func_72939_s(World.java:1887)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:18)
> 	at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:93)
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
> 	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
> 	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
> 	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
> 	at net.minecraft.world.World.func_72866_a(World.java:2070)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
> 	at net.minecraft.world.World.func_72870_g(World.java:2034)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: Zombie (net.minecraft.entity.monster.EntityZombie)
> 	Entity ID: 9004
> 	Entity Name: Zombie
> 	Entity's Exact location: -177.81, 68.00, 203.45
> 	Entity's Block location: World: (-178,68,203), Chunk: (at 14,4,11 in -12,12; contains blocks -192,0,192 to -177,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.06, -0.08, -0.02
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1887)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> 
> -- Affected level --
> Details:
> 	Level name: New World
> 	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/287, l='New World', x=-176.00, y=68.00, z=200.19]]
> 	Chunk stats: ServerChunkCache: 712 Drop: 0
> 	Level seed: -4443592127145540400
> 	Level generator: ID 00 - default, ver 1. Features enabled: true
> 	Level generator options: 
> 	Level spawn location: World: (-176,64,204), Chunk: (at 0,4,12 in -11,12; contains blocks -176,0,192 to -161,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 2311 game time, 13424 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 113744 (now: false), thunder time: 155667 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_31, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 340136688 bytes (324 MB) / 598736896 bytes (571 MB) up to 954728448 bytes (910 MB)
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 5 mods loaded, 5 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
> 	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
> 	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal (1).jar) 
> 	UCHIJAAAA	MCA{1.7.10-5.1.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.2-universal.jar) 
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Profiler Position: N/A (disabled)
> 	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/287, l='New World', x=-176.00, y=68.00, z=200.19]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> [19:45:24] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:354]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Arianna\Desktop\MultiMC\instances\MCA Villager Zombie Crash\minecraft\crash-reports\crash-2016-02-05_19.45.24-server.txt
> [19:45:24] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
> [19:45:24] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
> [19:45:24] [Server thread/INFO]: Saving chunks for level 'New World'/The End
> [19:45:25] [Server thread/INFO] [FML]: Unloading dimension 0
> [19:45:25] [Server thread/INFO] [FML]: Unloading dimension -1
> [19:45:25] [Server thread/INFO] [FML]: Unloading dimension 1
> [19:45:25] [Server thread/INFO] [FML]: Applying holder lookups
> [19:45:25] [Server thread/INFO] [FML]: Holder lookups applied
> [19:45:25] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
> [19:45:25] [Client thread/INFO] [FML]: Server terminated.
> AL lib: (EE) alc_cleanup: 1 device not closed
> Process exited with code -1.
> 

------------------------------------------------------------------------------------------------------------------------------

I initially had this occur once in a while on a heavily modded pack, and decided to see if I could recreate it with nothing other than MCA. In order to replicate the crash, create a world in creative, set the game to night, create a small enclosed area, and spawn a couple MCA villagers along with some zombies. It looks like it crashes when the MCA villager gets converted to a zombie, but the zombies continue to attack the converted villager. Even then, it does not crash with a 100% success rate.

Edited in: I'm using MultiMC. This is on 1.7.10, running Forge 10.13.4.1566, MCA 5.1.1.2, RadixCore 2.1.1 and nothing else for the above crash.

**Comment by mezzodrinker** [comment]
See #576 and #210.

**Comment by Ariannae** [comment]
Thank you mezzodrinker, just didn't see it!

**Comment by WildBamaBoy** [comment]
Reopening so I remember to take another look at this to see if there's any kind of workaround I could come up with.

**Comment by Ariannae** [comment]
Just a little bit more information on this issue as well. It doesn't look like I'm able to reproduce it without MCA/RadixCore loaded, and it looks like it's only happening when the MCA villagers turn into their infected counterpart. It does not seem to occur if they turn into a vanilla zombie villager. However, it is not a 100% chance to crash when the MCA villagers turns into their infected counterpart and baby zombies can also crash the game in the same fashion. The world is able to be reloaded normally, and the MCA villager is using the corresponding infected villager skin.

**Comment by kotoroshinoto** [comment]
it is reproducible on my server, as i've had it happen to me, but if it isn't reliable every time, that makes it hard to debug. the problem with that is it is hard to be quite sure the problem is fixed if you have to "rinse and repeat" to make it happen. Unless of course the  offending code has an obvious error in it.

**Comment by spruill7716** [comment]
I'm still recieving the same crash with the newest 1.7.10 version.
[https://www.dropbox.com/s/1lqxemm6k3wuqdg/crash-2016-06-06_18.19.15-server.txt?dl=0]

**Comment by Andre-Maartens** [comment]
Me too. Albeit now I can't even create a world although not your issue

**Comment by cocopuffs99** [comment]
Temporary fix:  https://github.com/Mithion/ArsMagica2/issues/1032

Change MCA.config "Enable infection" of villagers and children to "false".

**Comment by Robijnvogel** [comment]
I just confirmed that this issue [still occurs](https://paste.dimdev.org/tiqezagoge.mccrash) without Ars Magica installed on the latest 1.7.10 version of MCA and RadixCore.

**Comment by Robijnvogel** [comment]
I see that your code [here](https://github.com/WildBamaBoy/minecraft-comes-alive/blob/df2791130ba5956791b07fba765d3a23d59d6301/src/main/java/mca/core/forge/EventHooksForge.java#L357-L371) is meant to interrupt Zombies trying to re-aggro the infected Villager. You have to do this **every time** that a Zombie tries to target a Villager.

The way I see it, it is more processor efficient to split the uninfected and infected villagers in two separate classes and then use an Interface for their mutual functionality. *(You would need to copy their fields or store them externally, sadly.)* Replacing the Entity with another entity will automatically de-aggro every mob that is hunting it and if the infected villagers don't extend EntityVillager, then the zombies will not re-aggro them. Until you cure them, that is.
